// Conservative local parser: detects material headings and retains source text.
// Every extracted block remains a draft until reviewed by the user.
export const nextDay=s=>{const d=new Date(s+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)};
function iso(d,m,y){const s=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const t=new Date(s+'T12:00:00Z');return !isNaN(t)&&t.toISOString().slice(0,10)===s?s:''}
export function ranges(text,year){const found=[];const re=/(\d{1,2})\.(\d{1,2})\.?\s*(?:–|—|-)\s*(\d{1,2})\.(\d{1,2})(?:\.(\d{4}))?/g;for(const m of text.matchAll(re)){let y=Number(m[5]||year);const a=iso(+m[1],+m[2],y),b=iso(+m[3],+m[4],y+(+m[4]<+m[2]?1:0));if(a&&b&&!found.some(x=>x.start===a&&x.end===b))found.push({start:a,end:b});}return found}
function joinItems(items){let text='',prev=null;for(const i of items){text+=(prev && i.x-(prev.x+prev.width)>1?' ':'')+i.text;prev=i}return text.replace(/\s+/g,' ').trim()}
export function linesFromItems(items){const rows=[];for(const it of items){if(!it.str?.trim())continue;const y=it.transform[5],x=it.transform[4];let row=rows.find(r=>Math.abs(r.y-y)<3);if(!row){row={y,items:[]};rows.push(row)}row.items.push({x,text:it.str,size:Math.abs(it.transform[3]),width:it.width})}return rows.sort((a,b)=>b.y-a.y).map(r=>({...r,text:joinItems(r.items.sort((a,b)=>a.x-b.x)),left:joinItems(r.items.filter(i=>i.x<395))}))}
const keywords=/PLAKAT|WOB[BL]*LER|WOBLER|NAKLEJK|WKŁADK|OZNACZNIK|SHELFSTOP|CENNIK|LISTW|TOPPER|STAND|MATERIAŁY|KRAWAT|EKSPOZYTOR|OSŁON|PRZEGROD|ZAWIESZ|TABLICZK|WEEKEND ZACZYNA|ŻABKOBRANIE|CENOSPADANIE|KUPONOWANIE|MAXI OKAZJE|BUTELKA ZWROTNA|PIWA EKONOMICZNE/;
function heading(line){const t=line.left.replace(/^[➢•\s]+/,'').replace(/^\d\.\s*/,'');return t.length>7&&t.length<125&&t!=='MATERIAŁY'&&keywords.test(t)&&!/^\d{8}/.test(t)&&!/(MIEJSCE|OKRES|ZMIANA MATERIAŁ|DO USUNIĘCIA|POZOSTAJĄCE|NIESTANDARDOWYM|KOLOR PAPIERU|UWAGA|WAŻNE|PRZYKŁAD|POPRAWN|INDEKS|SAMODRUKI|MARKETINGOWE|DO ODWOŁANIA|MATERIAŁY Z)/.test(t)&&Math.max(...line.items.filter(i=>i.x<395).map(i=>i.size))>=14}
export function parsePages(pages){const all=pages.map(p=>p.lines.map(l=>l.text).join('\n')).join('\n');const year=Number(all.match(/20\d{2}/)?.[0]||new Date().getFullYear());const cycle=ranges(pages[0].lines.map(l=>l.text).join(' '),year)[0]||{start:'',end:''};let section='put';let tasks=[];const uncovered=[];
 for(const p of pages){const text=p.lines.map(l=>l.text).join('\n');if(/DO USUNIĘCIA/.test(text))section='remove';if(/ZMIANA MATERIAŁÓW|NOWE MATERIAŁY/.test(text))section='put';if(/MATERIAŁY POZOSTAJĄCE/.test(text))section='keep';const heads=p.lines.map((l,i)=>heading(l)?i:-1).filter(i=>i>=0);if(!heads.length)uncovered.push(p.page);
 for(let h=0;h<heads.length;h++){const i=heads[h],end=heads[h+1]??p.lines.length;const block=p.lines.slice(i,end).filter(l=>!l.text.startsWith('Informacje handlowe'));const near=p.lines.slice(Math.max(0,i-2),i).filter(l=>l.items.every(z=>z.x>390));const source=[...near,...block].map(l=>l.text).join('\n');const rs=ranges(source,year);const conflicting=rs.length>1;const unlimited=/do odwołania/i.test(source);const prior=rs.length===1&&cycle.start&&rs[0].start<cycle.start;let action=section==='remove'?'remove':section==='keep'||prior?'keep':/SAMODRUKI/.test(text)?'print':'put';const date=action==='remove'?cycle.start:!conflicting&&rs.length===1?rs[0].start:'';const finish=action!=='remove'&&!conflicting&&!unlimited&&rs.length===1?rs[0].end:'';tasks.push({id:`p${p.page}-${i}`,title:p.lines[i].left.replace(/^[➢•\s]+/,''),action,start:date,end:finish,page:p.page,source,notes:'',status:'draft',done:false,issues:[...(conflicting?['Kilka okresów lub rozbieżne daty — wybierz właściwe.']:[]),...(unlimited?['Materiał lub jeden z wariantów obowiązuje do odwołania.']:[]),...(/tylko|wyłącznie|nie dotyczy|nie obowiązuje|dla sklepów|sklepy FLEX/i.test(source)?['Sprawdź wariant i wyposażenie sklepu.']:[]),...(!date?['Uzupełnij datę lub wybierz „Pozostaje”.']:[])],indices:[...new Set(source.match(/\b\d{8}\b/g)||[])]});}}
 return {cycle,tasks,uncovered};}
export function eventsFor(tasks,date){return tasks.filter(t=>t.status==='approved').flatMap(t=>{const out=[];if(t.action!=='keep'&&t.start===date)out.push({...t,eventKey:t.id+':start',eventAction:t.action});if(t.action==='put'&&t.end&&nextDay(t.end)===date)out.push({...t,eventKey:t.id+':end',eventAction:'remove'});return out})}
