import test from 'node:test';
import assert from 'node:assert/strict';
import {warsawTime} from '../calendar.mjs';
import {desiredEvents,reconcile} from '../calendar-sync.mjs';
const options={putTime:'05:45',removeTime:'23:05',alarm:true};
const task={id:'t1',title:'Plakat',status:'approved',action:'put',start:'2026-09-23',end:'2026-09-29',indices:[],source:'Miejsce ekspozycji: przy kasie',notes:'',page:1};
const state=()=>({profile:{facts:{}},docs:[{id:'doc',name:'T39_23.09-29.09.2026.pdf',tasks:[{...task}],completed:{}}]});
test('Warsaw summer/winter and invalid DST time',()=>{assert.equal(warsawTime('2026-09-23','05:45').toISOString(),'2026-09-23T03:45:00.000Z');assert.equal(warsawTime('2026-12-23','23:05').toISOString(),'2026-12-23T22:05:00.000Z');assert.throws(()=>warsawTime('2026-03-29','02:30'));});
test('approved events, completion, undo, draft and keep',()=>{const s=state();let out=desiredEvents(s,options);assert.equal(Object.keys(out).length,2);assert.equal(out['doc:t1:end'].start.dateTime,'2026-09-30T21:05:00.000Z');s.docs[0].completed['t1:start']=true;assert.equal(Object.keys(desiredEvents(s,options)).length,1);s.docs[0].completed={};assert.equal(Object.keys(desiredEvents(s,options)).length,2);s.docs[0].tasks[0].status='draft';assert.deepEqual(desiredEvents(s,options),{});s.docs[0].tasks[0].status='approved';s.docs[0].tasks[0].action='keep';assert.deepEqual(desiredEvents(s,options),{});});
const error=status=>Object.assign(Error('simulated'),{status});
function service(){const remote=new Map(),calls=[];let sequence=0;const api=async(method,id,body)=>{calls.push([method,id]);if(method==='POST'){if(remote.has(id))throw error(409);remote.set(id,body)}if(method==='PATCH'){if(!remote.has(id)||remote.get(id)===null)throw error(410);remote.set(id,body)}if(method==='DELETE')remote.set(id,null)};return {remote,calls,api,newId:()=>String(++sequence),persist:async()=>{}}}
test('idempotent create, update, delete and undo with a new event id',async()=>{const x=service(),j={},d={key:{summary:'Wywieś'}};await reconcile(j,d,x.api,x.persist,x.newId);await reconcile(j,d,x.api,x.persist,x.newId);assert.equal(x.calls.length,1);const old=j.key.id;await reconcile(j,{key:{summary:'Zmienione'}},x.api,x.persist,x.newId);assert.equal(x.calls.at(-1)[0],'PATCH');await reconcile(j,{},x.api,x.persist,x.newId);assert.equal(x.remote.get(old),null);await reconcile(j,d,x.api,x.persist,x.newId);assert.notEqual(j.key.id,old);});
test('lost create response retries same id without duplicates',async()=>{const x=service(),j={},d={k:{summary:'Wywieś'}};let fail=true;const api=async(...args)=>{await x.api(...args);if(fail){fail=false;throw error(503)}};await assert.rejects(reconcile(j,d,api,x.persist,x.newId));const id=j.k.id;assert.equal(j.k.fingerprint,null);await reconcile(j,d,api,x.persist,x.newId);assert.equal(j.k.id,id);assert.equal(x.remote.size,1)});
test('offline/expired failures keep journal for later deletion',async()=>{const j={k:{id:'1',fingerprint:'x'}};await assert.rejects(reconcile(j,{},async()=>{throw error(401)},async()=>{},()=>''));assert.ok(j.k);await reconcile(j,{},async()=>{throw error(410)},async()=>{},()=> '');assert.deepEqual(j,{})});
test('failed pending insert and tombstone receive a new id',async()=>{const x=service(),j={k:{id:'old',fingerprint:null}};x.remote.set('old',null);await reconcile(j,{k:{summary:'test'}},x.api,x.persist,x.newId);assert.notEqual(j.k.id,'old')});
test('profile excludes material and settings update times/reminders',()=>{const s=state();s.profile={city:'Warszawa',facts:{region:'mazowieckie'}};s.docs[0].tasks[0].source='Materiał obowiązuje tylko w sklepach w Wielkopolsce.';assert.deepEqual(desiredEvents(s,options),{});s.docs[0].tasks[0].source='';const events=desiredEvents(s,{...options,putTime:'06:00',alarm:false});assert.equal(events['doc:t1:start'].start.dateTime,'2026-09-23T04:00:00.000Z');assert.deepEqual(events['doc:t1:start'].reminders.overrides,[])});
test('newer cycle version wins to avoid duplicate imports',()=>{const s=state();s.docs[0].created='2026-09-20';s.docs.push({...s.docs[0],id:'new',created:'2026-09-22'});const events=desiredEvents(s,options);assert.ok(events['new:t1:start']);assert.equal(events['doc:t1:start'],undefined);assert.equal(events['doc:t1:end'],undefined)});
