import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const code=await readFile(new URL('../sw.js',import.meta.url),'utf8');
function worker({fail=false}={}){const handlers={},calls=[];let skipped=0;const cache={addAll:async requests=>{assert.ok(requests.every(r=>r.options.cache==='reload'));if(fail)throw Error('offline')},match:async request=>{calls.push(['match',request]);return 'cached-response'}};const context={Request:class{constructor(path,options){this.path=path;this.options=options}},URL,Promise,Response:{error:()=>null},fetch:async()=>{},caches:{open:async key=>{calls.push(['open',key]);return cache},keys:async()=>[],delete:async()=>{}},self:{location:'https://example.test/marketing/sw.js',addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting:async()=>{skipped++},clients:{claim:async()=>{}}}};context.self.location=new URL(context.self.location);vm.runInNewContext(code,context);return {handlers,calls,skipped:()=>skipped}}
test('complete download waits for user before activation',async()=>{const w=worker();let done;w.handlers.install({waitUntil:p=>done=p});await done;assert.equal(w.skipped(),0);w.handlers.message({data:{type:'ACTIVATE_UPDATE'},waitUntil:p=>done=p});await done;assert.equal(w.skipped(),1)});
test('failed download never activates incomplete version',async()=>{const w=worker({fail:true});let done;w.handlers.install({waitUntil:p=>done=p});await assert.rejects(done);assert.equal(w.skipped(),0)});
test('active worker reads only its own cache',async()=>{const w=worker();let done;w.handlers.fetch({request:{method:'GET',url:'https://example.test/marketing/app.mjs'},respondWith:p=>done=p});assert.equal(await done,'cached-response');assert.equal(w.calls[0][0],'open');assert.equal(w.calls[0][1],'marketing-sklepu-v15')});
